# Generated by Django 4.2.6 on 2023-10-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('photo_2', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=30)),
                ('meta', models.CharField(max_length=255)),
                ('verbose_text', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
    ]
